---
- name: Validate Disk Space
  hosts: "{{ target_host }}"
  gather_facts: false

  tasks:

    - name: Recalculate disk utilization
      ansible.windows.win_shell: |
        $drive = "{{ drive_letter }}:"
        $disk = Get-CimInstance Win32_LogicalDisk |
        Where-Object {$_.DeviceID -eq $drive}

        $used_pct = [math]::Round((($disk.Size - $disk.FreeSpace) / $disk.Size) * 100,2)

        $result = @{
            drive = $drive
            used_pct = $used_pct
            free_gb = [math]::Round($disk.FreeSpace / 1GB,2)
        }

        $result | ConvertTo-Json -Compress

      register: validation

    - name: Display results
      debug:
        var: validation.stdout

    - name: Fail if utilization still critical
      fail:
        msg: "Disk usage still above threshold"
      when:
        - (validation.stdout | from_json).used_pct | float > disk_threshold | float

    - name: Success
      debug:
        msg: >
          Disk utilization reduced to
          {{ (validation.stdout | from_json).used_pct }}%
